/* T571 — the runtime's view of the SQLSA layout.
 *
 * The runtime cannot include preprocessor output, so it addresses the program's
 * SQLSA by offset. That makes the published layout encoded twice: once as a C
 * struct in src/pp/sqlsa.cc, once as these constants. Exactly the drift
 * Principle VI exists to prevent — add a field to one side only and the runtime
 * writes over the wrong bytes of the program's own memory, silently.
 *
 * tests/harness/sqlsa_layout_sync.sh compares the two, in both directions.
 * Change one side and that test fails; change neither and it passes for the
 * right reason. Do not edit this file without running it.
 *
 * Offsets are from §9 pp.9-15..9-16 under packed alignment, with the manual's
 * `long` read as 32-bit TNS. Both totals are reachable only packed: v300
 * measures 840 naturally against a published 838, v330 1864 against 1790.
 */
#ifndef ESQLC_RT_SQLSA_OFFSETS_H
#define ESQLC_RT_SQLSA_OFFSETS_H

/* Totals and strides */
#define SQLSA_V300_LEN      838
#define SQLSA_V330_LEN     1790
#define SQLSA_V300_STRIDE    52
#define SQLSA_V330_STRIDE   108
#define SQLSA_MAX_TABLES     16   /* FR-005.22 */

/* Header, identical in both families */
#define SQLSA_OFF_EYE         0
#define SQLSA_OFF_VERSION     2
#define SQLSA_OFF_UNION       4   /* dml and prepare both start here */

/* v300 dml arm */
#define SQLSA_V300_OFF_NUM_TABLES   4
#define SQLSA_V300_OFF_STATS        6
#define SQLSA_V300_S_TABLE_NAME     0
#define SQLSA_V300_S_RECS_ACCESSED 24
#define SQLSA_V300_S_RECS_USED     28
#define SQLSA_V300_S_DISC_READS    32
#define SQLSA_V300_S_MESSAGES      36
#define SQLSA_V300_S_MSG_BYTES     40
#define SQLSA_V300_S_WAITS         44
#define SQLSA_V300_S_ESCALATIONS   46
#define SQLSA_V300_S_RESERVED      48

/* v330 dml arm: three timing fields and a filler precede stats[] */
#define SQLSA_V330_OFF_NUM_TABLES   4
#define SQLSA_V330_OFF_STATS       62   /* 4 + 2 + 3*8 + 32; 62 + 16*108 = 1790 */
#define SQLSA_V330_S_TABLE_NAME     0
#define SQLSA_V330_S_RECS_ACCESSED 24
#define SQLSA_V330_S_RECS_USED     32
#define SQLSA_V330_S_DISC_READS    40
#define SQLSA_V330_S_MESSAGES      48
#define SQLSA_V330_S_MSG_BYTES     56
#define SQLSA_V330_S_WAITS         64
#define SQLSA_V330_S_ESCALATIONS   68
#define SQLSA_V330_S_VSBB_WRITE    72
#define SQLSA_V330_S_VSBB_FLUSHED  74

/* FR-005.23, and the precedent SD-7 follows: the one sentinel the manual
 * publishes for itself. */
#define SQLSA_VSBB_TRUE  (-1)
#define SQLSA_VSBB_FALSE   0

/* SD-8: an unmappable character field is '?' to its full declared width.
 * Visibly not a table name, distinguishable from both an empty string and a
 * blank-padded one, and safe to print. */
#define SQLSA_CHAR_SENTINEL '?'

typedef struct {
    const char *field;
    unsigned    off;
} esqlc_sqlsa_off_t;

/* The table the sync harness reads. Not part of the public ABI — generated
 * code never calls this; only the test does. */
const esqlc_sqlsa_off_t *esqlc_rt_sqlsa_offsets(int version, int *n);

#endif
