/* generated by esqlcpp from tests/conformance/gate-1/hostvar_spans.sqlc — do not edit */
#include "esqlc.h"
#line 1 "tests/conformance/gate-1/hostvar_spans.sqlc"

#line 2 "tests/conformance/gate-1/hostvar_spans.sqlc"

  short a;
  char  b[11];
#line 5 "tests/conformance/gate-1/hostvar_spans.sqlc"

int main(void) {
  #line 7 "tests/conformance/gate-1/hostvar_spans.sqlc"
do {
  esqlc_hostvar_t __esqlc_hv_1[2] = {
    { &a, 0, ESQLC_T_INT, 2u, 2u, 0, 1, ESQLC_DIR_IN, 0 },
    { &b, 0, ESQLC_T_CHAR_FIXED, 10u, 11u, 0, 1, ESQLC_DIR_IN, 0 },
  };
  esqlc_stmt_exec("INSERT INTO t (x, y, z) VALUES (?, \"literal :alsonot\", ?)", 57, __esqlc_hv_1, 2);
  sqlcode = esqlc_sqlcode();
} while (0);
#line 9 "tests/conformance/gate-1/hostvar_spans.sqlc"

  return 0;
}

/* host variable layout assertions (NFR-002.2) */
_Static_assert(sizeof(a) == 2, "a width drifted");
_Static_assert(sizeof(b) == 11, "b capacity drifted");
