/* generated by esqlcpp from tests/conformance/gate-1/insert.sqlc — do not edit */
#include "esqlc.h"
#line 1 "tests/conformance/gate-1/insert.sqlc"


#include <stdio.h>
#include <string.h>

long sqlcode;            /* program-declared, per slice decision SD-2 */

#line 8 "tests/conformance/gate-1/insert.sqlc"

  short part_num;
  char  part_desc[19];
#line 11 "tests/conformance/gate-1/insert.sqlc"


int main(void)
{
  part_num = 4102;
  /* 18 characters exactly - blank padded by the program, per FR-002.31 */
  memcpy(part_desc, "HEX NUT, 8MM      ", 18);
  part_desc[18] = '\0';

  
#line 20 "tests/conformance/gate-1/insert.sqlc"
do { esqlc_txn_begin();
  sqlcode = esqlc_sqlcode();
} while (0);
#line 20 "tests/conformance/gate-1/insert.sqlc"


  
#line 22 "tests/conformance/gate-1/insert.sqlc"
do {
  esqlc_hostvar_t __esqlc_hv_1[2] = {
    { &part_num, 0, ESQLC_T_INT, 2u, 2u, 0, 1, ESQLC_DIR_IN, 0 },
    { &part_desc, 0, ESQLC_T_CHAR_FIXED, 18u, 19u, 0, 1, ESQLC_DIR_IN, 0 },
  };
  esqlc_stmt_exec("INSERT INTO parts (part_num, part_desc) VALUES (?, ?)", 53, __esqlc_hv_1, 2);
  sqlcode = esqlc_sqlcode();
} while (0);
#line 23 "tests/conformance/gate-1/insert.sqlc"


  if (sqlcode != 0) {
    /* Save it first: every statement resets sqlcode, ROLLBACK WORK included,
       so reporting it after the rollback reports the rollback's status, not
       the failure's. The manual gives this advice at §9 p.9-13. */
    long failed_with = sqlcode;
    
#line 30 "tests/conformance/gate-1/insert.sqlc"
do { esqlc_txn_rollback();
  sqlcode = esqlc_sqlcode();
} while (0);
#line 30 "tests/conformance/gate-1/insert.sqlc"

    fprintf(stderr, "insert failed, sqlcode %ld\n", failed_with);
    return 1;
  }

  
#line 35 "tests/conformance/gate-1/insert.sqlc"
do { esqlc_txn_commit();
  sqlcode = esqlc_sqlcode();
} while (0);
#line 35 "tests/conformance/gate-1/insert.sqlc"

  return 0;
}

/* host variable layout assertions (NFR-002.2) */
_Static_assert(sizeof(part_num) == 2, "part_num width drifted");
_Static_assert(sizeof(part_desc) == 19, "part_desc capacity drifted");
